export enum ErrorTypes {
    UNKNOWN = 'UNKNOWN',
    PERMISSIONS_CALLBACK = 'PERMISSIONS_CALLBACK',
    CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
    INSTRUCTION_NOT_FOUND = 'INSTRUCTION_NOT_FOUND',
    NUTRITION_NOT_FOUND = 'NUTRITION_NOT_FOUND',
}
